In [2]:
import sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read the data

In [24]:
database = 'database.sqlite'

In [29]:
data = sqlite3.connect(database)
tables = pd.read_sql("SELECT * FROM sqlite_master WHERE type='table'", data)

In [41]:
tables.name

0      sqlite_sequence
1    Player_Attributes
2               Player
3                Match
4               League
5              Country
6                 Team
7      Team_Attributes
Name: name, dtype: object

# Countries and Leagues

In [84]:
leagues = pd.read_sql("SELECT * FROM League JOIN Country on Country.id == League.id", data)

In [85]:
leagues

       id  country_id                      name     id         name
0       1           1    Belgium Jupiler League      1      Belgium
1    1729        1729    England Premier League   1729      England
2    4769        4769            France Ligue 1   4769       France
3    7809        7809     Germany 1. Bundesliga   7809      Germany
4   10257       10257             Italy Serie A  10257        Italy
5   13274       13274    Netherlands Eredivisie  13274  Netherlands
6   15722       15722        Poland Ekstraklasa  15722       Poland
7   17642       17642  Portugal Liga ZON Sagres  17642     Portugal
8   19694       19694   Scotland Premier League  19694     Scotland
9   21518       21518           Spain LIGA BBVA  21518        Spain
10  24558       24558  Switzerland Super League  24558  Switzerland

# Teams

In [48]:
teams = pd.read_sql("SELECT * FROM Team", data)

In [73]:
print('number of teams:', len(teams["team_long_name"].unique()))

number of teams: 296

# Player Attributes

In [88]:
player_attributes = pd.read_sql("SELECT * FROM Player_Attributes", data)

In [89]:
player_attributes.columns

Index(['id', 'player_fifa_api_id', 'player_api_id', 'date', 'overall_rating',
       'potential', 'preferred_foot', 'attacking_work_rate',
       'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes'],
      dtype='object')

In [90]:
player_attributes.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,183978.0,91989.500000,53110.018250,1.0,45995.25,91989.5,137983.75,183978.0
player_fifa_api_id,183978.0,165671.524291,53851.094769,2.0,155798.00,183488.0,199848.00,234141.0
player_api_id,183978.0,135900.617324,136927.840510,2625.0,34763.00,77741.0,191080.00,750584.0
overall_rating,183142.0,68.600015,7.041139,33.0,64.00,69.0,73.00,94.0
potential,183142.0,73.460353,6.592271,39.0,69.00,74.0,78.00,97.0
crossing,183142.0,55.086883,17.242135,1.0,45.00,59.0,68.00,95.0
finishing,183142.0,49.921078,19.038705,1.0,34.00,53.0,65.00,97.0
heading_accuracy,183142.0,57.266023,16.488905,1.0,49.00,60.0,68.00,98.0
short_passing,183142.0,62.429672,14.194068,3.0,57.00,65.0,72.00,97.0
volleys,181265.0,49.468436,18.256618,1.0,35.00,52.0,64.00,93.0
dribbling,183142.0,59.175154,17.744688,1.0,52.00,64.0,72.00,97.0
curve,181265.0,52.965675,18.255788,2.0,41.00,56.0,67.00,94.0
free_kick_accuracy,183142.0,49.380950,17.831746,1.0,36.00,50.0,63.00,97.0
long_passing,183142.0,57.069880,14.394464,3.0,49.00,59.0,67.00,97.0
ball_control,183142.0,63.388879,15.196671,5.0,58.00,67.0,73.00,97.0
acceleration,183142.0,67.659357,12.983326,10.0,61.00,69.0,77.00,97.0
sprint_speed,183142.0,68.051244,12.569721,12.0,62.00,69.0,77.00,97.0
agility,181265.0,65.970910,12.954585,11.0,58.00,68.0,75.00,96.0
reactions,183142.0,66.103706,9.155408,17.0,61.00,67.0,72.00,96.0
balance,181265.0,65.189496,13.063188,12.0,58.00,67.0,74.00,96.0
shot_power,183142.0,61.808427,16.135143,2.0,54.00,65.0,73.00,97.0
jumping,181265.0,66.969045,11.006734,14.0,60.00,68.0,74.00,96.0
stamina,183142.0,67.038544,13.165262,10.0,61.00,69.0,76.00,96.0
strength,183142.0,67.424529,12.072280,10.0,60.00,69.0,76.00,96.0
long_shots,183142.0,53.339431,18.367025,1.0,41.00,58.0,67.00,96.0
aggression,183142.0,60.948046,16.089521,6.0,51.00,64.0,73.00,97.0
interceptions,183142.0,52.009271,19.450133,1.0,34.00,57.0,68.00,96.0
positioning,183142.0,55.786504,18.448292,2.0,45.00,60.0,69.00,96.0
vision,181265.0,57.873550,15.144086,1.0,49.00,60.0,69.00,97.0
penalties,183142.0,55.003986,15.546519,2.0,45.00,57.0,67.00,96.0
marking,183142.0,46.772242,21.227667,1.0,25.00,50.0,66.00,96.0
standing_tackle,183142.0,50.351257,21.483706,1.0,29.00,56.0,69.00,95.0
sliding_tackle,181265.0,48.001462,21.598778,2.0,25.00,53.0,67.00,95.0
gk_diving,183142.0,14.704393,16.865467,1.0,7.00,10.0,13.00,94.0
gk_handling,183142.0,16.063612,15.867382,1.0,8.00,11.0,15.00,93.0
gk_kicking,183142.0,20.998362,21.452980,1.0,8.00,12.0,15.00,97.0
gk_positioning,183142.0,16.132154,16.099175,1.0,8.00,11.0,15.00,96.0
gk_reflexes,183142.0,16.441439,17.198155,1.0,8.00,11.0,15.00,96.0

# Match

In [101]:
matches = pd.read_sql("""SELECT Match.id,
                                Country.name as country_name,
                                League.name as league_name,
                                season,
                                stage,
                                date,
                                HT.team_long_name AS home_team,
                                AT.team_long_name AS away_team,
                                home_team_goal,
                                away_team_goal
                      FROM Match
                      JOIN Country ON Country.id == Match.country_id
                      JOIN League ON League.id == Match.league_id
                      JOIN Team AS HT on HT.team_api_id == Match.home_team_api_id
                      JOIN Team AS AT on AT.team_api_id == Match.away_team_api_id
                      WHERE country_name == 'Italy'
                      ORDER by date""", data)

In [102]:
matches

,id,country_name,league_name,season,stage,date,home_team,away_team,home_team_goal,away_team_goal
0,10264,Italy,Italy Serie A,2008/2009,1,2008-08-30 00:00:00,Sampdoria,Inter,1,1
1,10266,Italy,Italy Serie A,2008/2009,1,2008-08-30 00:00:00,Udinese,Palermo,3,1
2,10257,Italy,Italy Serie A,2008/2009,1,2008-08-31 00:00:00,Atalanta,Siena,1,0
3,10258,Italy,Italy Serie A,2008/2009,1,2008-08-31 00:00:00,Cagliari,Lazio,1,4
4,10259,Italy,Italy Serie A,2008/2009,1,2008-08-31 00:00:00,Catania,Genoa,1,0
...,...,...,...,...,...,...,...,...,...,...
3012,13205,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Chievo Verona,Bologna,0,0
3013,13206,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Udinese,Carpi,1,2
3014,13207,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Lazio,Fiorentina,2,4
3015,13209,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Palermo,Hellas Verona,3,2
3016,13213,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Empoli,Torino,2,1